// this file is automatically generated by GenProjectPlugin.fsx
// (note, in Xamarin you may need to close/reopen this file to see changes)
#r "packages/FunScript/lib/net40/FunScript.Interop.dll"
#r "packages/FunScript/lib/net40/FunScript.dll"
#r "packages/FunScript.TypeScript.Binding.lib/lib/net40/FunScript.TypeScript.Binding.lib.dll"
#r "packages/FunScript.TypeScript.Binding.three/lib/net40/FunScript.TypeScript.Binding.three.dll"
#load "Project.fsx"
#load "FunscriptWebServer.fs"
#load "WebMain.fs"
