// this file is automatically generated by GenProjectPlugin.fsx
#r "packages/Nancy/lib/net40/Nancy.dll"
#r "packages/Nancy.Hosting.Self/lib/net40/Nancy.Hosting.Self.dll"
#r "System.Net.Http.dll"
#r "packages/Fuchu/lib/Fuchu.dll"
#load "WebServer.fs"
#load "WebModules.fs"
#load "Program.fs"
